### ISSUE TITLE
Too many buckets error on Monitor List on the Overview page

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#194]
**Describe the bug**
I tried to set the page size to 100 items on the Overview list, and the page told me there was an internal server error.

**To Reproduce**
1. Create 100+ monitors, let them run for some time (> 15m).
2. Attempt to set the page size of the monitor list to 100 items.
![image](https://user-images.githubusercontent.com/18429259/81433469-9a386180-9132-11ea-8d35-bf8ed5a312d5.png)
3. You should see an internal server error message in the list's error view:
![image](https://user-images.githubusercontent.com/18429259/81433622-dbc90c80-9132-11ea-834a-ace6eca09b8a.png)

*Additional context:* Choosing 50 items also resulted in a long wait time.

**Expected behavior**
I should see the monitor list with each row displaying a corresponding histogram.

**Debug logs**
I've included the server logs below:

<details>
<summary>Click to expand</summary>

```
server    log   [13:51:06.566] [error][http] { Error: [too_many_buckets_exception] Trying to create too many buckets. Must be less than or equal to: [10000] but was [10001]. This limit can be set by changing the [search.max_buckets] cluster level setting., with { max_buckets=10000 }
    at respond (/Users/jk/git/justinkambic/kibana/node_modules/elasticsearch/src/lib/transport.js:349:15)
    at checkRespForFailure (/Users/jk/git/justinkambic/kibana/node_modules/elasticsearch/src/lib/transport.js:306:7)
    at HttpConnector.<anonymous> (/Users/jk/git/justinkambic/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)
    at IncomingMessage.wrapper (/Users/jk/git/justinkambic/kibana/node_modules/elasticsearch/node_modules/lodash/lodash.js:4929:19)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  status: 503,
  displayName: 'ServiceUnavailable',
  message:
   '[too_many_buckets_exception] Trying to create too many buckets. Must be less than or equal to: [10000] but was [10001]. This limit can be set by changing the [search.max_buckets] cluster level setting., with { max_buckets=10000 }',
  path: '/heartbeat-8*/_search',
  query: {},
  body:
   { error:
      { root_cause: [Array],
        type: 'search_phase_execution_exception',
        reason: 'all shards failed',
        phase: 'query',
        grouped: true,
        failed_shards: [Array] },
     status: 503 },
  statusCode: 503,
  response:
   '{"error":{"root_cause":[{"type":"too_many_buckets_exception","reason":"Trying to create too many buckets. Must be less than or equal to: [10000] but was [10001]. This limit can be set by changing the [search.max_buckets] cluster level setting.","max_buckets":10000}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"heartbeat-8.0.0-2020.05.08-000001","node":"bag6XfXmR6KUkymuTTh6NQ","reason":{"type":"too_many_buckets_exception","reason":"Trying to create too many buckets. Must be less than or equal to: [10000] but was [10001]. This limit can be set by changing the [search.max_buckets] cluster level setting.","max_buckets":10000}}]},"status":503}',
  toString: [Function],
  toJSON: [Function] }
server   error  [13:51:06.125]  Error: Internal Server Error
    at HapiResponseAdapter.toInternalError (/Users/jk/git/justinkambic/kibana/src/core/server/http/router/response_adapter.ts:56:19)
    at Router.handle (/Users/jk/git/justinkambic/kibana/src/core/server/http/router/router.ts:266:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
</details>

**Comment by shahzad31** [comment]
Resolved by https://github.com/elastic/kibana/pull/66832
