### ISSUE TITLE
Certain searches trigger internal server error

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#209]
**Describe the bug**
For certain search queries, parsing can result in a query like:

```JSON
{
  "multi_match": {
    "type": "best_fields",
    "query": "some text",
    "lenient": true
  }
}
```

**To Reproduce**
1. Type some non-query syntax text into the search bar.
2. Wait a moment for the parsing to happen.
3. Check your Kibana server log and see the error.
4. You can also see the error in your browser's network tab. Filter for `500` status code.

This error happens because we have some custom parsing code on the back end that compiles the DSL from the user's search into a larger query that gets passed to Elasticsearch.

**Expected behavior**
We should handle this output without an error. If the query is `multi_match` we'll have to append it to our filters list.

**Debug logs**

<details>
<summary>Click to expand</summary>

```
server    log   [19:19:20.846] [error][http] TypeError: Cannot set property 'filter' of undefined
    at combineRangeWithFilters (/Users/jk/git/justinkambic/kibana/x-pack/plugins/uptime/server/lib/requests/get_filter_bar.ts:44:3)
    at Object.getFilterBar (/Users/jk/git/justinkambic/kibana/x-pack/plugins/uptime/server/lib/requests/get_filter_bar.ts:84:19)
    at handler (/Users/jk/git/justinkambic/kibana/x-pack/plugins/uptime/server/rest_api/overview_filters/get_overview_filters.ts:43:49)
    at Object.handler (/Users/jk/git/justinkambic/kibana/x-pack/plugins/uptime/server/rest_api/create_route_with_auth.ts:19:14)
    at handler (/Users/jk/git/justinkambic/kibana/x-pack/plugins/uptime/server/rest_api/uptime_route_wrapper.ts:19:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
server   error  [19:19:20.756]  Error: Internal Server Error
    at HapiResponseAdapter.toInternalError (/Users/jk/git/justinkambic/kibana/src/core/server/http/router/response_adapter.ts:56:19)
    at Router.handle (/Users/jk/git/justinkambic/kibana/src/core/server/http/router/router.ts:266:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
</details>

**Comment by shahzad31** [comment]
this is fixed in this PR https://github.com/elastic/kibana/pull/66888
