### ISSUE TITLE
heartbeat error message summary contains stack trace data

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/uptime#275]
Heartbeat should only use the `error.message` data instead of `error.stack` from synthetics agent as part of the generating the monitor summary

## Heartbeat data
```json
{
  "_index": "heartbeat-8.0.0-2020.11.30-000001",
  "_id": "WUSiGHYBzKz6bhBZ_Gn0",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2020-11-30T10:10:00.087Z",
    "url": {
      "full": "https://www.elastic.co/",
      "scheme": "https",
      "domain": "www.elastic.co",
      "port": 443,
      "path": "/"
    },
    "synthetics": {
      "type": "heartbeat/summary"
    },
    "monitor": {
      "status": "down",
      "check_group": "20272f9e-32f4-11eb-9d3b-025000000001",
      "duration": {
        "us": 30800907
      },
      "id": "my-monitor",
      "name": "My Monitor",
      "type": "browser",
      "timespan": {
        "gte": "2020-11-30T10:10:00.025Z",
        "lt": "2020-11-30T10:11:00.025Z"
      }
    },
    "event": {
      "dataset": "uptime"
    },
    "ecs": {
      "version": "1.6.0"
    },
    "agent": {
      "version": "8.0.0",
      "ephemeral_id": "f7d9afc3-38a5-4cde-bd27-17d7a382832a",
      "id": "5a53b585-9103-4858-acb6-fa7cfc197329",
      "name": "docker-desktop",
      "type": "heartbeat"
    },
    "error": {
      "type": "io",
      "message": "error executing step: TimeoutError: page.goto: Timeout 30000ms exceeded.\npage.goto: Timeout 30000ms exceeded.\n=========================== logs ===========================\nnavigating to \"https://www.elastic.co\", waiting until \"load\"\n============================================================\nNote: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.: \n    at Connection.sendMessageToServer (/usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/node_modules/playwright-chromium/lib/client/connection.js:69:15)\n    at Proxy.<anonymous> (/usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/node_modules/playwright-chromium/lib/client/channelOwner.js:54:53)\n    at /usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/node_modules/playwright-chromium/lib/client/frame.js:80:71\n    at Frame._wrapApiCall (/usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/node_modules/playwright-chromium/lib/client/channelOwner.js:80:34)\n    at Frame.goto (/usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/node_modules/playwright-chromium/lib/client/frame.js:78:21)\n    at /usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/node_modules/playwright-chromium/lib/client/page.js:267:60\n    at Page._attributeToPage (/usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/node_modules/playwright-chromium/lib/client/page.js:202:20)\n    at Page.goto (/usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/node_modules/playwright-chromium/lib/client/page.js:267:21)\n    at Step.eval [as callback] (eval at loadInlineScript (/usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/src/cli.ts:52:20), <anonymous>:2:16)\n    at Runner.runStep (/usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/src/core/runner.ts:184:18)"
    },
    "summary": {
      "down": 1,
      "up": 0
    }
  },
  "fields": {
    "@timestamp": [
      "2020-11-30T10:10:00.087Z"
    ]
  },
  "highlight": {
    "monitor.name": [
      "@kibana-highlighted-field@My Monitor@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1606731000087
  ]
}
```

## Synthetics document
```json
{
  "_index": "heartbeat-8.0.0-2020.11.30-000001",
  "_id": "WESiGHYBzKz6bhBZ_Gn0",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2020-11-30T10:10:00.045Z",
    "ecs": {
      "version": "1.6.0"
    },
    "agent": {
      "type": "heartbeat",
      "version": "8.0.0",
      "ephemeral_id": "f7d9afc3-38a5-4cde-bd27-17d7a382832a",
      "id": "5a53b585-9103-4858-acb6-fa7cfc197329",
      "name": "docker-desktop"
    },
    "synthetics": {
      "error": {
        "message": "page.goto: Timeout 30000ms exceeded.",
        "stack": "page.goto: Timeout 30000ms exceeded.\n=========================== logs ===========================\nnavigating to \"https://www.elastic.co\", waiting until \"load\"\n============================================================\nNote: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.: \n    at Connection.sendMessageToServer (/usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/node_modules/playwright-chromium/lib/client/connection.js:69:15)\n    at Proxy.<anonymous> (/usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/node_modules/playwright-chromium/lib/client/channelOwner.js:54:53)\n    at /usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/node_modules/playwright-chromium/lib/client/frame.js:80:71\n    at Frame._wrapApiCall (/usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/node_modules/playwright-chromium/lib/client/channelOwner.js:80:34)\n    at Frame.goto (/usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/node_modules/playwright-chromium/lib/client/frame.js:78:21)\n    at /usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/node_modules/playwright-chromium/lib/client/page.js:267:60\n    at Page._attributeToPage (/usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/node_modules/playwright-chromium/lib/client/page.js:202:20)\n    at Page.goto (/usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/node_modules/playwright-chromium/lib/client/page.js:267:21)\n    at Step.eval [as callback] (eval at loadInlineScript (/usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/src/cli.ts:52:20), <anonymous>:2:16)\n    at Runner.runStep (/usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/src/core/runner.ts:184:18)",
        "name": "TimeoutError"
      },
      "type": "journey/end",
      "package_version": "0.0.1-alpha.6",
      "payload": {
        "end": 1239.4316111,
        "status": "failed",
        "start": 1207.982452579
      },
      "journey": {
        "id": "inline",
        "name": "inline"
      }
    },
    "monitor": {
      "name": "My Monitor",
      "type": "browser",
      "check_group": "20272f9e-32f4-11eb-9d3b-025000000001",
      "timespan": {
        "gte": "2020-11-30T10:10:00.025Z",
        "lt": "2020-11-30T10:11:00.025Z"
      },
      "id": "my-monitor"
    },
    "event": {
      "dataset": "uptime"
    }
  },
  "fields": {
    "@timestamp": [
      "2020-11-30T10:10:00.045Z"
    ]
  },
  "highlight": {
    "monitor.name": [
      "@kibana-highlighted-field@My Monitor@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1606731000045
  ]
}
```

**Comment by andrewvc** [comment]
Fixed in https://github.com/elastic/beats/commit/862883fb0119cab9f0722b85d119ee8c3e6e28fc
